apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:      
  name: fleetman-webapp-hpa      
spec:
  maxReplicas: 4
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fleetman-webapp