apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fleetman-webapp-pdb
spec:
  # maxUnavailable: 1 
  minAvailable: 1
  selector:
    matchLabels:
      app: web
      type: webapp
      tier: prod      
