apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: resizable-sc
allowVolumeExpansion: true
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2